spring:
  application:
    name: jova-server-v2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDB_HOST:localhost}:${RDB_PORT:3306}/${RDB_NAME}?serverTimezone=Asia/Seoul
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: update